version: "3.9"

services:
  db:
    image: postgres:14
    container_name: the-hive-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thehive
    ports:
      - "5433:5432"
    volumes:
      - hive-db-data:/var/lib/postgresql/data

  web:
    build: .
    container_name: the-hive-web
    command: python app.py
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://dev-db-023163:AVNS_7GGf-O3O8mXuIoen6BZ@app-2d3dbb24-06fd-4ea8-84d8-3bf2f0401edf-do-user-17857016-0.m.db.ondigitalocean.com:25060/dev-db-023163?sslmode=require

volumes:
  hive-db-data:

