version: "3.9"

services:
  db:
    image: postgres:14
    container_name: the-hive-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thehive
    ports:
      - "5433:5432"
    volumes:
      - hive-db-data:/var/lib/postgresql/data

  web:
    build: .
    container_name: the-hive-web
    command: python app.py
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@the-hive-db:5432/thehive

volumes:
  hive-db-data:

